<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-04-02 15:42

from django.db import migrations, models
import main_page.utils
=======
# Generated by Django 4.1.7 on 2023-03-15 14:28

from django.db import migrations, models
>>>>>>> f54e6daafcc4fe9a70b2717eb1659f61a822a314


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
<<<<<<< HEAD
            field=models.ImageField(default=None, upload_to=main_page.utils.get_file_name_id),
            preserve_default=False,
=======
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/'),
>>>>>>> f54e6daafcc4fe9a70b2717eb1659f61a822a314
        ),
    ]
